databases:
  - name: onlibrary-production
    ipAllowList: []

services:
  - type: web
    name: onlibrary
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: onlibrary-production
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction


